### ISSUE TITLE
Request to add pt_PT langcode for translation

### ISSUE THREAD

**Issue by zekroman** [Sudomemo/sudomemo-locales#331]
I would like to request the addition of a European Portuguese Langcode, and for the Brazilian users, also add the pt_BR Langcode so a proper translation for both dialects is avaliable.

**Comment by Vento5886** [comment]
I would like to help in the European version

**Comment by sudofox** [comment]
We'll be considering this soon, once we can get all the other languages updated. Would you be willing to actively help maintain it when it gets updated with new text?

**Comment by Vento5886** [comment]
I dont mind, but if it will be everyday, it will be a little hard :P

But I accept the challenge

**Comment by Vento5886** [comment]
Sorry to say this at the moment. But I just can do the revision (ex.grammar). I don't knoe how to programme and I dont have the specs to do any programming.

**Comment by meemo** [comment]
Hi there, you don't need programming skills in order to translate, all translating entails is replacing text in certain files. If you're still willing to help out, could you DM SudoModMail in the [Sudomemo Discord](https://flipnot.es/discord)? We can help you out if you're having any issues in our translator server.

**Comment by meemo** [comment]
Done in #420
